/**
 * Image Service - Legacy Wrapper
 * Now uses the unified mediaGenerationService for all image operations
 */

import { generateAIImage, searchStockImage, ImageGenerationResult } from './mediaGenerationService';

export interface ImageRequest {
    keyword: string;
    width?: number;
    height?: number;
    orientation?: 'landscape' | 'portrait' | 'squarish';
    useAI?: boolean; // If true, generate AI image instead of stock
}

export const imageService = {
    /**
     * Get a high-quality image URL
     * Uses AI generation (Stability AI/Replicate) or stock photos (Unsplash/Pixabay)
     */
    async getImageUrl(request: ImageRequest): Promise<string> {
        const { keyword, width = 800, height = 600, useAI = false } = request;

        try {
            if (useAI) {
                const result = await generateAIImage({
                    prompt: `${keyword}, high quality, professional, detailed`,
                    width,
                    height
                });
                console.log(`🎨 Image generated by: ${result.provider}`);
                return result.url;
            } else {
                const results = await searchStockImage(keyword, 1);
                if (results.length > 0) {
                    console.log(`📷 Stock image from: ${results[0].provider}`);
                    return results[0].url;
                }
            }
        } catch (error) {
            console.warn('Image service error, using fallback:', error);
        }

        // Fallback to Pollinations
        const encodedPrompt = encodeURIComponent(keyword);
        return `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&nologo=true`;
    },

    /**
     * Get a gallery of images
     */
    async getGalleryImages(keyword: string, count: number = 3): Promise<string[]> {
        try {
            const results = await searchStockImage(keyword, count);
            return results.map(r => r.url);
        } catch (error) {
            // Fallback
            return Array.from({ length: count }).map((_, i) =>
                `https://image.pollinations.ai/prompt/${encodeURIComponent(keyword + ' ' + i)}?width=800&height=600&nologo=true`
            );
        }
    },

    /**
     * Get a hero background image (AI-generated for uniqueness)
     */
    async getHeroImage(keyword: string): Promise<string> {
        return this.getImageUrl({
            keyword: `${keyword} wallpaper background aesthetic high-quality cinematic`,
            width: 1920,
            height: 1080,
            useAI: true // Use AI for hero images
        });
    },

    /**
     * Get an avatar image
     */
    async getAvatar(gender: 'male' | 'female' | 'any' = 'any'): Promise<string> {
        const term = gender === 'any' ? 'professional headshot portrait' : `${gender} professional headshot portrait`;
        return this.getImageUrl({
            keyword: term,
            width: 200,
            height: 200,
            useAI: false // Stock photos for avatars
        });
    },

    // Sync versions for backwards compatibility
    getImageUrlSync(request: ImageRequest): string {
        const { keyword, width = 800, height = 600 } = request;
        return `https://image.pollinations.ai/prompt/${encodeURIComponent(keyword)}?width=${width}&height=${height}&nologo=true`;
    },

    getGalleryImagesSync(keyword: string, count: number = 3): string[] {
        return Array.from({ length: count }).map((_, i) =>
            `https://image.pollinations.ai/prompt/${encodeURIComponent(keyword + ' ' + ['modern', 'detail', 'perspective'][i % 3])}?width=800&height=600&nologo=true`
        );
    },

    getHeroImageSync(keyword: string): string {
        return `https://image.pollinations.ai/prompt/${encodeURIComponent(keyword + ' wallpaper background aesthetic high-quality')}?width=1920&height=1080&nologo=true`;
    },

    getAvatarSync(gender: 'male' | 'female' | 'any' = 'any'): string {
        const term = gender === 'any' ? 'person portrait' : `${gender} portrait business`;
        return `https://image.pollinations.ai/prompt/${encodeURIComponent(term)}?width=200&height=200&nologo=true`;
    }
};

